### ISSUE TITLE
Add routes in the main.dart file

### ISSUE THREAD

**Issue by sanjay14073** [gdsc-jssstu/campUS-flutter#1]
The UI/UX design for the app is here
https://www.figma.com/proto/fg2pUtJ4oJmUfScwGD7oRo/CampusUs-Mobile-version?page-id=0%3A1&type=design&node-id=2-1718&viewport=646%2C313%2C0.12&t=tqwzJk8lSFjigPaY-1&scaling=scale-down&starting-point-node-id=2%3A1718&mode=design

**Adding Routes**
Add the following route by creating screens in the screen folder.The routes to be created are as follows.
Login
Signup
Request
Myrequests
MyProfile
About Us

Your Pull request you only be accepted if your answer is compilling without any issues and solves the raised issue

**Comment by JULIUSANGULU** [comment]
I would like to take up this issue.

**Comment by sanjay14073** [comment]
@JULIUSANGULU  sure the issue is assigned to you

**Comment by sanjay14073** [comment]
@JULIUSANGULU  any update

**Comment by sikehish** [comment]
Given that there's no update, I'd like to take up the issue.

**Comment by sanjay14073** [comment]
@JULIUSANGULU sorry since you havent replied the issue is begin assigned to @sikehish

**Comment by JULIUSANGULU** [comment]
> @JULIUSANGULU sorry since you havent replied the issue is begin assigned to @sikehish

Ohhh I'm sorry, I was working on it but I understand. Thank you for assigning it to me in the first place:)

**Comment by sikehish** [comment]
Hi @sanjay14073 . Ive created a PR. Please look into it, and let me know if any changes are to be made
