### ISSUE TITLE
Create an User Model for App

### ISSUE THREAD

**Issue by sanjay14073** [gdsc-jssstu/campUS-flutter#5]
The UI/UX design for the app is here
https://www.figma.com/proto/fg2pUtJ4oJmUfScwGD7oRo/CampusUs-Mobile-version?page-id=0%3A1&type=design&node-id=2-1718&viewport=646%2C313%2C0.12&t=tqwzJk8lSFjigPaY-1&scaling=scale-down&starting-point-node-id=2%3A1718&mode=design

**Creating the user model**
Create an User Model that consists of the following fields
Name
Year
Contact Number
Issue
Your Would be required to create an User Model in the Models.dart folder
Your Pull request you only be accepted if your answer is compilling without any issues and solves the raised issue

**Comment by sikehish** [comment]
Hi. Ive started working on this. Can you assign it to me?

**Comment by sanjay14073** [comment]
@sikehish  sure the issue is assigned to you

**Comment by sikehish** [comment]
Ive implemented it. It's done. Please review it

**Comment by sanjay14073** [comment]
Done by @sikehish
